### ISSUE TITLE
wipe should cause enumeration to reset

### ISSUE THREAD

**Issue by kojq** [sentriz/cliphist#66] opened 2023-11-03 15:55 UTC
After performing `cliphist wipe`, enumeration continues from the last number rather than resetting.

**Comment by sentriz** [comment] 2023-11-03 16:26
hi, dupe of #44

**Comment by sentriz** [comment] 2023-11-03 16:27
basically you can just `$ rm $XDG_CACHE_HOME/cliphist/db`

**Closed as completed by sentriz** 2023-11-03 16:26 UTC
